# Workflow build, test, dan deploy Java Maven tanpa Sonar
name: Maven CI/CD Safe

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ 192.168.56.1 }}
          username: ${{ LEGION }}
          key: ${{ -----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEArJ9L3WhSKtglqe5w+KgcUtojWUOn6qBizdKY1zp/NwLpI/MR1csEMCqxFPIgevakwMoOWmkPToF9erMDTtSkEsbpyqjPCb4HG9n2rtoLB8jbzgpuDiE8uJRIHFZe0l53C4eMhmfTXKJMD/2fAH10EWz3efdNv0wEjrVFNfDcwlbfAJB+67kuzP1nNPVbKsla+eD2wjkRNwZcHIAk1dI05XhaEWQSR2rXogQaOfPKT3STTXzuLlhDFxBHvNWa1jefZxFXH3DPXiXtGBneSYgzZ9XlpYMpXr21jhHLGxRWzQcF4gyInA0MmwSi20UZeCdRlsltmSzczyBzTUOtTbFT33Mxf7IZo0SAzpfUo0JLTFesyZN2yQczoAUlhbyzVmxsLtCGTLsuSC4rmLhjKQepeHoGMd810/fs9sA8a9OM244Y+QcgZMMnvlFJTY/ItqIZ93FFGWb1HmAtMmRu3ah8RVOsPIrGJY626RBIt1BPpyMgblHhurel0VDYcPUDYKgBOJVfmXzGpD8CtJPr/ba4jpNMihj6pFcLOKxHDyyKJX1Pv3xgLu3pDjZuKmJQbs0kKRONYcnomulz2wwsS9Vggg/pM06ZQH1MM/XpcYnRQPPKR3XLSLbswbU3U7obzKZMPdrLGnSXp1B/WnjHS4K/koisi4Uu2cNM7UhcFSXZWK0AAADAQABAAACACZupNZbhoexbdlCk/ZYf03W8S3LiVQMd1L5wzuP84jM5hkx4dOmin0q1BgkvCSESzP9CGsKnvTMkaJCvsbLQuhHTv/my4mQvEZwJaLSOsh16LIb0lrk/X7ezJs6g4v0qi5v9FJsRTuHisW4orDaPYAvsX1/GNkxVIZtR0Z2JMBD1QxsH0XeCdRrypGY2r5Q7Cdb9bRSPknw6YsS4KCWV16LiAn9LLCn0fBpV2l1pKJCAxWqbeD1l6JH5qDdMcblxWCOFMaUOCbu7LWD9OCMKV3B2ooaBJjqRcSmo4CY66ZkHOQyBCwyH49X3eZRoRUGM/0NRZBn05Vt1R3rpmb4xwJH6rdzg5cHtlKbZJrXITV4GV2ZeRwG4kA4J0AwwzysMmhhbbs3xcqSzpzCdhagIR3TzQ3Cs00u+LCbnV28C+kZo+mFWD+/r3Yfz8dWqiHLDtJPEpsD0IyH6t37WzvIo2Teo5NN00oC/od/0hSyx8Ys75DAbEQo6/KZz2SAajDyB5AHPbwcLlM/veFqaEKMHTzn4Jygzgx/+R/RZhI6Z8Vy8T11OdDtv1H3eBg7IUKsLdk2iV41RYmmc9REUG3rutJ5RE9+MlNTckIcgv0KH6ItqxNskyeeH1sZ4vBG9oHVXAZif2P0fUupdcOasqsi76MHKZQgl7B6aMo443dmFJZlAAABAQDUXRhhzR4hi9BoCmG5aMT9p6TFKnxnmgr2npO4l5TjBXi7KMn1zWYoxHRTQjih7VHfBqjbkc5mPcWbSelD1BZkFEIZv7z5mOsd1m9C/161JFT4TlYmkLODj37pNzM/a68/CpdBwXkJ4dzPEkurCv9v7nURe/xFGGniteFvT2BBGuGK58PHHR5RbvscVfftqkttE6k4qaXFljZc71uz3JAHjHWkUGNIIThLVV8T9VOsKZPk5GUoOhZMfaNwVUCGxyczX71b1Qu0FKKcMCv6bK0yiLXZfJOdWCiq3DTO2JVxOkFe3d8ChXeFQHOY5gWkOseGVNPUSEd0cBhQ50/5mSmgAAABAQDh85V7no9pbRFZJz4gUF6oUMcO8Q6kzK+HBvpFn1yyA9J1mrUu/z3P8O8a8xHBODqIDDvyWp/vTkaTfjSoVVQhQwt8lLQ+0T/3clXKEU1+5Wb65WAn7jQo7ByWZLfyNmtbRd1lpEb5HUQgnyuGfJc9AL+jplWuuZthSIi5Cyf51d8S2dkysOoAPAxLlK3wYTpiamsXE4kDoOD7ETUgSJ/QiUkid3aqClctserJckQsh3TM849n/fwwCBvNoT2LnQjLeVB7duycckrmTN2yvesQ5R2k99JpdpMArfnP8V5PAlqjvEk1+4N2pFzjCVco/PO6unNxBb5LV88x8kFni7WjAAABAQDDlCR1WBDMMVUIOzUrUDRZ4f09S2ZGAmMJiqtBrk/QbOCT3p1mF9/8e3tLc9OVHnKU9F8YOgBS1nQqUoAPsec6o5aZ1NnNN2O2djjE3bQar2iMmuJP00YS11xDCzuOz5a8r60JwGjVoVIDF4/g+cRs1tu4DpMI4r6mspaZt+CZqvQwyL/jKGxKlOEWpD9dExQG0ZW1w0q7cljFViQmXO4brttwC86kifW1cqbzfzvQV9U8d5iK8PkC6KNB5k2183A2Z6Bj5s492OsHsnJPP1VNUa2M2KbuwP2cIXJN19Cc+ud4J2zWFu9uPnzLyya6vFt80v/GnVeThB3ChLN8Z31vAAAADmdpdGh1Yi1hY3Rpb25zAQIDBA==-----END OPENSSH PRIVATE KEY----- }}
          port: 22
          script: |
            cd /var/www/app
            mv target/*.jar app.jar
            systemctl restart app.service